


export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';
export const ADD_TODO_STARTED = 'ADD_TODO_STARTED';
export const DELETE_TODO = 'DELETE_TODO';